{
  "updated_at": "2026-04-26",
  "source": "Editable starter data for DNVR Vibes. Replace with Google Sheets export data when ready.",
  "places": [
    {
      "id": 101,
      "name": "Cherry Cricket",
      "category": "Burgers",
      "neighborhood": "Cherry Creek",
      "vibe_score": 96,
      "trend_score": 88,
      "description": "A Denver burger institution with a lively room, classic energy, and the kind of menu that works for almost any group.",
      "best_for": "Classic Denver burger nights",
      "why_it_hits": "It feels familiar, social, and dependable without losing the fun of a real night out.",
      "tags": ["classic", "group-friendly", "local energy", "casual"],
      "local_pick": true,
      "visitor_friendly": true,
      "image_url": "",
      "website_url": "https://www.cherrycricket.com/",
      "map_url": "https://maps.google.com/?q=Cherry+Cricket+Denver"
    },
    {
      "id": 102,
      "name": "My Brother's Bar",
      "category": "Burgers",
      "neighborhood": "Highland",
      "vibe_score": 94,
      "trend_score": 82,
      "description": "Old-school Denver character, low-friction service, and a burger stop that feels more like a ritual than a trend.",
      "best_for": "Low-key local hangs",
      "why_it_hits": "The appeal is the atmosphere as much as the burger: simple, steady, and very Denver.",
      "tags": ["old-school", "local", "low-key", "historic"],
      "local_pick": true,
      "visitor_friendly": true,
      "image_url": "",
      "website_url": "https://mybrothersbar.com/",
      "map_url": "https://maps.google.com/?q=My+Brother%27s+Bar+Denver"
    },
    {
      "id": 103,
      "name": "Crown Burgers",
      "category": "Burgers",
      "neighborhood": "South Denver",
      "vibe_score": 91,
      "trend_score": 78,
      "description": "A satisfying no-fuss burger move when the plan is less about scene and more about getting something craveable.",
      "best_for": "Quick comfort-food stops",
      "why_it_hits": "It is practical, filling, and easy to recommend when everyone just wants a good burger without overthinking it.",
      "tags": ["quick bite", "comfort food", "casual", "easy"],
      "local_pick": true,
      "visitor_friendly": false,
      "image_url": "",
      "website_url": "",
      "map_url": "https://maps.google.com/?q=Crown+Burgers+Denver"
    },
    {
      "id": 104,
      "name": "Park Burger",
      "category": "Burgers",
      "neighborhood": "Platt Park",
      "vibe_score": 90,
      "trend_score": 83,
      "description": "Bright, approachable, and easy to fold into a casual Denver day when the group wants burgers and no drama.",
      "best_for": "Casual lunch and neighborhood dinners",
      "why_it_hits": "It has an easygoing rhythm, broad appeal, and a neighborhood feel that keeps it useful.",
      "tags": ["neighborhood", "lunch", "family-friendly", "casual"],
      "local_pick": true,
      "visitor_friendly": true,
      "image_url": "",
      "website_url": "https://parkburger.com/",
      "map_url": "https://maps.google.com/?q=Park+Burger+Denver"
    },
    {
      "id": 105,
      "name": "Hopdoddy Burger Bar",
      "category": "Burgers",
      "neighborhood": "Union Station",
      "vibe_score": 89,
      "trend_score": 84,
      "description": "A polished, visitor-friendly burger option with a lively pace and easy access to downtown plans.",
      "best_for": "Visitors and downtown meetups",
      "why_it_hits": "It is simple to find, easy to coordinate, and energetic enough to feel like part of the night.",
      "tags": ["downtown", "visitor-friendly", "meetup", "lively"],
      "local_pick": false,
      "visitor_friendly": true,
      "image_url": "",
      "website_url": "https://www.hopdoddy.com/",
      "map_url": "https://maps.google.com/?q=Hopdoddy+Burger+Bar+Denver"
    },
    {
      "id": 106,
      "name": "Illegal Burger",
      "category": "Burgers",
      "neighborhood": "Capitol Hill",
      "vibe_score": 88,
      "trend_score": 80,
      "description": "A casual burger stop with enough personality to work before a show, after errands, or during a loose night out.",
      "best_for": "Casual pregame bites",
      "why_it_hits": "It fits the middle of the plan: fast enough to be easy, fun enough to feel intentional.",
      "tags": ["casual", "quick bite", "pregame", "cap hill"],
      "local_pick": true,
      "visitor_friendly": true,
      "image_url": "",
      "website_url": "https://www.illegalburger.com/",
      "map_url": "https://maps.google.com/?q=Illegal+Burger+Denver"
    },
    {
      "id": 107,
      "name": "The Mighty",
      "category": "Burgers",
      "neighborhood": "LoHi",
      "vibe_score": 87,
      "trend_score": 86,
      "description": "A more current-feeling burger pick with a social edge, good for turning a quick meal into a night-starting move.",
      "best_for": "Friend hangs and first stops",
      "why_it_hits": "The draw is the mix of casual food and neighborhood momentum.",
      "tags": ["lohi", "social", "friends", "night out"],
      "local_pick": true,
      "visitor_friendly": true,
      "image_url": "",
      "website_url": "",
      "map_url": "https://maps.google.com/?q=The+Mighty+Denver+burger"
    },
    {
      "id": 108,
      "name": "Bodega Denver",
      "category": "Burgers",
      "neighborhood": "Sunnyside",
      "vibe_score": 86,
      "trend_score": 90,
      "description": "A buzzy food stop that works when you want something more current than a standard burger run.",
      "best_for": "Trending casual food plans",
      "why_it_hits": "It feels plugged into the city’s current food conversation and gives the category a fresher angle.",
      "tags": ["trending", "sunnyside", "casual", "buzz"],
      "local_pick": true,
      "visitor_friendly": true,
      "image_url": "",
      "website_url": "https://www.bodegadenver.com/",
      "map_url": "https://maps.google.com/?q=Bodega+Denver"
    }
  ]
}
